package org.omg.PortableServer;


/**
* org/omg/PortableServer/THREAD_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, December 21, 2011 1:04:11 AM PST
*/

public interface THREAD_POLICY_ID
{

  /**
	 * The value representing THREAD_POLICY_ID.
	 */
  public static final int value = (int)(16L);
}
